version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: /test-ts
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    versioning-strategy: increase
