name: "Create Pull Request Action"
description: "ワークフロー実行中の変更ファイルをまとめてコミットし、プルリクエストを作成するアクション"

inputs:
  message:
    description: "コミットメッセージ"
    required: true

outputs:
  branch:
    description: "作成されたプルリクエストのブランチ名"
    value: ${{ steps.pr.outputs.branch }}

runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        USERNAME: github-actions[bot]
        EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        MESSAGE: ${{ inputs.message }}
        BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
        git config --global user.name "${USERNAME}"
        git config --global user.email "${EMAIL}"
        git switch -c ${BRANCH}
        git add .
        git commit -m "${MESSAGE}"
        git push origin "${BRANCH}"
        gh pr create --head "${BRANCH}" --title "${BRANCH}" --body "${MESSAGE}"
